<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\libs\MiniBank\MiniBank.csproj" />
    <ProjectReference Include="..\MiniBank.AccountsAndTransactions.Domain\MiniBank.AccountsAndTransactions.Domain.csproj" />
    <ProjectReference Include="..\MiniBank.AccountsAndTransactions.Infrastructure\MiniBank.AccountsAndTransactions.Infrastructure.csproj" />
  </ItemGroup>

</Project>
