POST {{HostAddress}}/accounts/
Content-Type: application/json

{
  "Name": "ChristianDC"
}
###

GET {{HostAddress}}/accounts/{accountId}

###

POST {{HostAddress}}/transactions/

###

GET {{HostAddress}}/transactions/{transactionId}

###
